apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: huinong-financial
data:
  app.yaml: |
    server:
      port: 8080
    database:
      host: mysql
      port: 3306
      username: root
      password: huinong123
      dbname: huinong_db
      charset: utf8mb4
      parseTime: true
      loc: Local
    redis:
      host: redis
      port: 6379
      password: ""
      db: 0

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: huinong-backend
  namespace: huinong-financial
spec:
  replicas: 2
  selector:
    matchLabels:
      app: huinong-backend
  template:
    metadata:
      labels:
        app: huinong-backend
    spec:
      containers:
      - name: backend
        image: huinong-backend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: GIN_MODE
          value: "release"
        - name: CONFIG_PATH
          value: "/app/config"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config-volume
        configMap:
          name: backend-config

---
apiVersion: v1
kind: Service
metadata:
  name: huinong-backend
  namespace: huinong-financial
spec:
  selector:
    app: huinong-backend
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP 