app:
  name: "数字惠农后端服务"
  version: "1.0.0"
  env: "development"
  port: 8080
  mode: "debug"  # debug, release, test

database:
  driver: "mysql"
  host: "10.10.10.10"
  port: 4000
  username: "root"
  password: ""
  database: "app"
  charset: "utf8mb4"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600

redis:
  host: "10.10.10.10"
  port: 6379
  password: ""
  database: 0
  pool_size: 100
  min_idle_conns: 10

jwt:
  secret_key: "huinong-jwt-secret-key-ChinaSkills@"
  expires_in: 86400  # 24小时
  refresh_expires_in: 604800  # 7天

dify:
  api_url: "http://172.18.120.57/v1"
  api_key: "app-HvWb6RgrJ79otrbz9e9OIivp"
  timeout: 30
  retry_times: 3
  workflows:
    loan_approval: "loan-approval-workflow-id"

sms:
  provider: "aliyun"
  access_key: "your-access-key"
  access_secret: "your-access-secret"
  sign_name: "数字惠农"
  template_codes:
    register: "SMS_123456789"
    login: "SMS_123456790"
    reset_password: "SMS_123456791"

file:
  storage_type: "local"  # local, oss, qiniu
  upload_path: "./uploads"
  max_file_size: 10485760  # 10MB
  allowed_types: ["jpg", "jpeg", "png", "pdf", "doc", "docx"]

log:
  level: "debug"  # debug, info, warn, error
  format: "json"  # text, json
  output: "both"  # console, file, both
  file_path: "./logs/app.log"
  max_size: 100  # MB
  max_age: 7     # days
  max_backups: 5

cors:
  allow_origins: ["*"]
  allow_methods: ["GET", "POST", "PUT", "DELETE", "OPTIONS"]
  allow_headers: ["Origin", "Content-Type", "Accept", "Authorization"]
  expose_headers: ["Content-Length"]
  allow_credentials: true
  max_age: 12

rate_limit:
  enabled: true
  requests_per_minute: 1000
  burst: 100

offline:
  enabled: true
  sync_interval: 300  # 5分钟同步一次
  queue_size: 10000
  retry_times: 3 